[package]
name = "py-rust-encode-varint"
version = "0.1.1"
edition = "2024"

[dependencies]
pyo3 = "0.27.1"
pyo3-file = { git = "https://github.com/omerbenamram/pyo3-file", rev = "92e0f505", version = "0.14.0" }
