[package]
name = "py-rust-encode-varint"
version = "0.3.6"
edition = "2021"

[lib]
name = "py_rust_encode_varint"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.1"
pyo3-file = { git = "https://github.com/omerbenamram/pyo3-file", rev = "92e0f505", version = "0.14.0" }
